name: Build Suite

on:
    push:
        branches: [ main ]

jobs:
    build-suite:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                benchmark:
                    - regex_coprocessor
                    - cva5
                    - zipcpu
                    - jt12
                    - vortex
        steps:
        - name: Git checkout
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        - name: git
          run: |
            # Setup git
            git config user.name "GitHub Actions Bot"
            git config user.email "chronbench@email.com"
        - name: python
          uses: actions/setup-python@v5
          with:
            python-version: '3.6.15'
        - name: build benchmarks
          run: python build_benchmark.py "${{ matrix.benchmark }}"
        - name: preserve benchmark
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.benchmark }}
            include-hidden-files: true
            path: |
                ${{ matrix.benchmark }}/
